// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYvAOR3R206BXQoZhg1OlZjJxf85mJ2s',
    appId: '1:412082315701:web:1980722aab79f8b036f9fc',
    messagingSenderId: '412082315701',
    projectId: 'seacole-tracker',
    authDomain: 'seacole-tracker.firebaseapp.com',
    storageBucket: 'seacole-tracker.appspot.com',
    measurementId: 'G-39W7CDS0LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Golwkr8gSYngUB5P5M6e1GQI3xfv0uY',
    appId: '1:412082315701:android:3b5d17084a60140636f9fc',
    messagingSenderId: '412082315701',
    projectId: 'seacole-tracker',
    storageBucket: 'seacole-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2thL-EaJl_EjyIQWM1zKX2U_LRG5Vjo',
    appId: '1:412082315701:ios:530f56ee8183d58a36f9fc',
    messagingSenderId: '412082315701',
    projectId: 'seacole-tracker',
    storageBucket: 'seacole-tracker.appspot.com',
    iosClientId:
        '412082315701-8tmij2gsiofe6pn5ntd2m2oh3dv1kfna.apps.googleusercontent.com',
    iosBundleId: 'com.example.bftracker',
  );
}
